//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_MasterPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProduct
    {
        public int PartnerProductId { get; set; }
        public int PartnerProductProductId { get; set; }
        public int PartnerProductPartnerId { get; set; }
        public int PartnerProductCountProduct { get; set; }
        public System.DateTime PartnerProductDate { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
