//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_MasterPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.PartnerProduct = new HashSet<PartnerProduct>();
        }
    
        public int PartnerId { get; set; }
        public int PartnerTypeId { get; set; }
        public string PartnerName { get; set; }
        public int PartnerDirectorId { get; set; }
        public string PartnerEmail { get; set; }
        public string PartnerPhone { get; set; }
        public int PartnerAdressId { get; set; }
        public string PartnerINN { get; set; }
        public string PartnerRating { get; set; }
    
        public virtual AdressPartners AdressPartners { get; set; }
        public virtual DirectorPartners DirectorPartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
        public virtual TypePartners TypePartners { get; set; }
    }
}
